#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <PROJECT_NAME> <GIT_URL> <LANGUAGE>"
    exit 1
fi

PROJECT_NAME=$1
GIT_URL=$2
LANGUAGE=$3

mkdir ~/projects/$PROJECT_NAME

cp -r ~/.local/scripts/default_project_$LANGUAGE/* ~/projects/$PROJECT_NAME/

cd ~/projects/$PROJECT_NAME || exit

git init
git add .
git commit -m "init autocommit"
git branch -M main
git remote add origin $GIT_URL
git push -u origin main

echo "Project $PROJECT_NAME has been set up and linked to remote repository $GIT_URL."

