#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <project> <command>"
    exit 1
fi

PROJECT="$1"
COMMAND="$2"
REMOTE_USER="main"
REMOTE_HOST="192.168.100.100"
PROJECT_DIR="$HOME/projects/$PROJECT"
BASE_DIR="$HOME/projects"

rsync -az --exclude 'env' "$PROJECT_DIR" "$REMOTE_USER@$REMOTE_HOST:$BASE_DIR"

ssh "$REMOTE_USER@$REMOTE_HOST" << EOF
    cd "$PROJECT_DIR"
    $COMMAND
    git restore .
EOF

