#!/bin/bash

if [[ -z $1 ]]; then
    DIRECTORY="./model"
else
    DIRECTORY=$1
fi

mkdir -p $DIRECTORY

cp -r ~/.local/scripts/default_sup_model/* $DIRECTORY

chmod a+w $DIRECTORY/*

echo "Directory '$DIRECTORY' has been created and populated with default files."

