#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <project_name> <remote_user> <remote_host>"
    exit 1
fi

## Arguments
PROJECT="$1"
REMOTE_USER="$2"
REMOTE_HOST="$3"
PROJECT_DIR=""$HOME"/projects/"$PROJECT""
BASE_DIR=""$HOME"/projects"

rsync -az --exclude "env" "$PROJECT_DIR" "$REMOTE_USER@$REMOTE_HOST:$BASE_DIR" && clear
ssh "$REMOTE_USER@$REMOTE_HOST"
