#!/bin/bash

DOTFILES_REPO="https://github.com/Jorgedavyd/.dotfiles.git"
DOTFILES_DIR="$HOME/.dotfiles"

install_stow() {
  if ! command -v stow &> /dev/null; then
    echo "stow not found, installing..."
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
      if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y stow
      elif command -v pacman &> /dev/null; then
        sudo pacman -Syu stow
      elif command -v yum &> /dev/null; then
        sudo yum install -y stow
      fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      if ! command -v brew &> /dev/null; then
        echo "Homebrew not found, installing..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      fi
      brew install stow
    fi
  else
    echo "stow is already installed"
  fi
}

clone_dotfiles() {
  if [ -d "$DOTFILES_DIR" ]; then
    echo "$DOTFILES_DIR already exists, pulling latest changes..."
    cd "$DOTFILES_DIR"
    git pull
  else
    echo "Cloning dotfiles repository..."
    git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
  fi
}

update_submodules() {
  echo "Initializing and updating submodules..."
  cd "$DOTFILES_DIR"
  git submodule update --init --recursive
}

set_permission() {
  chmod +x $DOTFILES_DIR/scripts/.local/scripts/*
}

stow_dotfiles() {
  echo "Creating symlinks using stow..."
  cd "$DOTFILES_DIR"
  for dir in */; do
    stow "${dir%/}"
  done
}

display_success_message() {
  echo "Dotfiles have been set up successfully."
}

main() {
  install_stow
  clone_dotfiles
  update_submodules
  set_permission
  stow_dotfiles
  display_success_message
}

main

