name: CD

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest pipreqs pip-tools setuptools wheel
          pipreqs {{NAME_PLACEHOLDER}} --savepath=./requirements.in
          sed -i 's/==.*$//' requirements.in
          sort requirements.in | uniq > requirements_unique.in
          pip-compile ./requirements_unique.in
          rm -f *.in
          pip install -r requirements_unique.txt
          rm -f requirements_unique.txt

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d/ -f3)" >> $GITHUB_ENV

      - name: Update version
        run: |
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ env.TAG_NAME }}/g" {{NAME_PLACEHOLDER}}/__init__.py

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

