name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        python_ver: [ "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest black pipreqs pip-tools
          pipreqs {{NAME_PLACEHOLDER}} --savepath=./requirements.in
          sed -i 's/==.*$//' requirements.in
          sort requirements.in | uniq > requirements_unique.in
          pip-compile ./requirements_unique.in
          rm -f *.in
          pip install -r requirements_unique.txt
          rm -f requirements_unique.txt

      - name: Run tests
        run: |
          pytest tests/
